### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by nicocharlery** [hollar/ex_ach#1]
## Object Model

*ACH file structure:*

|- File header record
|
|-+ Batch 1
| |- Company1/batch header record
| |- Entry detail records
| |- (Addenda record)
| |- Company1/batch control record
|
|-+ Batch 2
| |- Company2/batch header record
| |- Entry detail records
| |- (Addenda record)
| |- Company2/batch control record
|
|- file control record

## Tasks
- [ ] Obtain any related documents
- [ ] ~Complete Discovery using Eventstorming or Story Mapping~
- [ ] Create an object model
- [ ] ~Model the state transitions~
- [ ] Determine business rules
- [ ] Create a Feature List
- [ ] ~Identify UI components (mockup with Balsamiq Mockups)~

## Questions
- [ ] Is [Nacha.ex](https://github.com/InAbsentia/nacha.ex) [production-ready](https://github.com/InAbsentia/nacha.ex/issues/4)?
- [ ] Does Comerica Bank have special rules for  ACH files?
- [ ] Are the ACH details entries type WEB, or CCD, or CCD+?
- [ ] Do we need an addendum record if CCD+? 
*An addendum is required only for CCD+. The bank should tell us if that is necessary or not.*

## Feature List
* Creating the project
    - [ ] Setup a new mix project #8 
* Building a header
    - [ ] Generate a file header record #2 
* Building a batch
    - [ ] Generate a batch header record #3 
    - [ ] Generate batch entry details records #4 
    - [ ] Generate a batch control record #5 
*  Building a file control
    - [ ] Generate a file control record #6 
*  Creating a formatted file
    - [ ] Create a file with header, batches and file control records #7 

## Format specification rules:
- https://secureinstantpayments.com/sip/help/interface_specs/external/NACHA_format.pdf
-  https://content.pncmc.com/live/pnc/corporate/treasury-management/ach-conversion/ACH-File-Specifications.pdf
- http://www.rbcroyalbank.com/ach/file-889947.pdf

Official specification
- https://www.firstmid.com/wp-content/uploads/2014/02/2013-Corporate-Rules-and-Guidelines.pdf
(global definitions p.137)

## Links
- popular ruby gem: https://github.com/jm81/ach
- another one with maybe a nicer api: https://github.com/teampayoff/headache
